### ISSUE TITLE
GitHub Icon disappears on mobile

### ISSUE THREAD

**Issue by mundry** [ElianVanCutsem/elianvancutsem.github.io#168]
Hey,

putting the site into mobile view makes the GitHub logo disappear as it's a white logo on a white background.  :)

![2021-09-03_22-26](https://user-images.githubusercontent.com/1453314/132062293-0eac9b4b-8f97-4963-93c0-089a614b5106.png)

**Comment by ElianVanCutsem** [comment]
I noticed that too! Thanks for reaching out!
Normally it zhould be resolved already!

Right now fixed them black, but I would love them to be able to switch colors with the rest of the site.
